
# 📋 Análise estática e linting para o projeto Chat Simulator

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Regras recomendadas e adicionais
    always_declare_return_types: true
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_locals: true
    unnecessary_this: true
    use_key_in_widget_constructors: true
    sort_constructors_first: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    curly_braces_in_flow_control_structures: true
    annotate_overrides: true

analyzer:
  errors:
    unused_import: warning
    dead_code: warning
    missing_required_param: error
    missing_return: error
    invalid_assignment: error

# ✅ Execute: flutter analyze
# ✅ Ou ative o linting automático no VS Code / Android Studio
