name: chat_simulator
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: 6.1.5
  firebase_storage: ^12.4.7
  image_picker: ^1.0.7
  image_cropper: ^9.1.0
  shared_preferences: ^2.2.2

flutter:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
  uses-material-design: true

environment:
  sdk: '^3.8.0'