name: chat_simulator
version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  google_sign_in: ^7.0.0

environment:
  sdk: '^3.8.0'